version: "3"
services:
  database:
    image: alpine:latest
    command: >
      /bin/sh -c "
      apk update && apk add sqlite;
      sqlite3 /bitnami/sqlite/dev.sqlite3;
      "
    volumes:
      - ./data:/bitnami/sqlite

  nestjs-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - database

  react-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - nestjs-app
